### ISSUE TITLE
NXdetector_module/fast_axis_direction@depends_on is not validated

### ISSUE THREAD

**Issue by phyy-nx** [nexusformat/cnxvalidate#27]
I added a printf to validateDependsOnField in nxvgroup.c and ran it on a NeXus file using NXdetector_module.  I observed that the fast_axis_direction@depends_on attribute wasn't validated.

I don't anticipate this being fixed in time for the next milestone.  I'll put more details and steps to reproduce here after I finish with nexusformat/example_data#7.

**Comment by phyy-nx** [comment]
Example dataset:
https://zenodo.org/record/3352357
File: lyso009a_0087.JF07T32V01_master.h5

I'd hope the fast_axis_direction@depends_on attribute at /entry/instrument/ELE_D0/ARRAY_D0Q0M0A0 would be validated.  Comment from @mkoennecke indicates that depends_on attributes from fast/slow_axis_direction might not be checked.

**Comment by phyy-nx** [comment]
Added a printf to validateDependsOnAttributes in nxvgroup.c (printing fname).  Only `/entry/instrument/ELE_D0/transformations/AXIS_RAIL` was checked.

**Comment by mkoennecke** [comment]
I looked into this and this is by design. Depends_on chains are validated starting of the depends_on field. This field is missing in the example. NXdetector_module ought to specify the exact position of each pixel through the depends_on chain. Now, order of transformations is important. Thus we need the depends_on field to point us the very top of the dependency chain.

**Comment by mkoennecke** [comment]
Aaron, 

can you check that this works for you? If so, I will tag the current version as 1.0

**Comment by phyy-nx** [comment]
Ok, it's good thanks.  Appreciate the work on this and it's nice to know my data passes validation :)
